// SPDX-License-Identifier: MIT
// This file contains the bytecode for the BaseMoon contracts
// Auto-generated by extractBytecode.js

export const CONTRACT_BYTECODE = {
  BaseMoonNFT: "0x",
  BaseMoonToken: "0x",
  BaseMoonStorage: "0x"
} as const;

// If bytecode is not available, these will be empty strings
export const HAS_BYTECODE = !!CONTRACT_BYTECODE.BaseMoonNFT && CONTRACT_BYTECODE.BaseMoonNFT !== "0x" &&
                           !!CONTRACT_BYTECODE.BaseMoonToken && CONTRACT_BYTECODE.BaseMoonToken !== "0x" &&
                           !!CONTRACT_BYTECODE.BaseMoonStorage && CONTRACT_BYTECODE.BaseMoonStorage !== "0x";